# Generated by Django 5.0.1 on 2024-03-06 22:49

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='Username')),
                ('password', models.CharField(max_length=20, verbose_name='Password')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('signature', models.CharField(default='Hey! write something here', max_length=100, verbose_name='Signature phrase')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=200, verbose_name='Title')),
                ('post_summary', models.CharField(max_length=100, verbose_name='Summary')),
                ('post_content', models.CharField(max_length=1000, verbose_name='Content')),
                ('post_publish_date', models.DateTimeField(default=datetime.datetime(2024, 3, 6, 16, 49, 24, 543119))),
                ('up_votes', models.IntegerField(default=0)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Noheru.user')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_content', models.CharField(max_length=500, verbose_name='Content')),
                ('up_votes', models.IntegerField(default=0)),
                ('comment_publish_date', models.DateTimeField(auto_now_add=True)),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='Noheru.comment')),
                ('parent_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Noheru.post')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Noheru.user')),
            ],
        ),
    ]
