# Generated by Django 5.0.1 on 2024-03-06 23:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Noheru', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_publish_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 6, 17, 1, 16, 452115)),
        ),
    ]
