# Generated by Django 5.0.1 on 2024-02-11 17:27

import django.db.models.deletion
import fernet_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=200, verbose_name='Title')),
                ('post_summary', models.CharField(max_length=100, verbose_name='Summary')),
                ('post_content', models.CharField(max_length=1000, verbose_name='Content')),
                ('post_publish_date', models.DateTimeField(auto_now_add=True)),
                ('up_votes', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20, unique=True, verbose_name='Username')),
                ('password', fernet_fields.fields.EncryptedCharField(max_length=20, verbose_name='Password')),
                ('email', fernet_fields.fields.EncryptedEmailField(max_length=254, verbose_name='Email')),
                ('signature', models.CharField(default='Hey! write something here', max_length=100, verbose_name='Signature phrase')),
            ],
        ),
        migrations.CreateModel(
            name='Responses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_content', models.CharField(max_length=500, verbose_name='Content')),
                ('up_votes', models.PositiveIntegerField()),
                ('response_publish_date', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Noheru.responses')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Noheru.posts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Noheru.users')),
            ],
        ),
        migrations.AddField(
            model_name='posts',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Noheru.users'),
        ),
    ]
