# Generated by Django 5.0.1 on 2024-02-11 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Noheru', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='up_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='responses',
            name='up_votes',
            field=models.IntegerField(default=0),
        ),
    ]
