# Generated by Django 5.0.1 on 2024-02-11 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Noheru', '0002_alter_posts_up_votes_alter_responses_up_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='post_publish_date',
            field=models.DateTimeField(),
        ),
    ]
