# Generated by Django 5.0.1 on 2024-02-11 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Noheru', '0004_alter_responses_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responses',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Noheru.responses'),
        ),
    ]
