# Generated by Django 5.0.1 on 2024-02-11 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Noheru', '0006_alter_responses_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Posts',
            new_name='Post',
        ),
        migrations.RenameModel(
            old_name='Responses',
            new_name='Response',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
