# Generated by Django 5.0.1 on 2024-02-18 15:37

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Noheru', '0007_rename_posts_post_rename_responses_response_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='creator',
        ),
        migrations.AlterField(
            model_name='post',
            name='post_publish_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 18, 9, 37, 52, 844175)),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_content', models.CharField(max_length=500, verbose_name='Content')),
                ('up_votes', models.IntegerField(default=0)),
                ('comment_publish_date', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Noheru.user')),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Noheru.comment')),
                ('parent_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Noheru.post')),
            ],
        ),
        migrations.DeleteModel(
            name='Response',
        ),
    ]
