# Generated by Django 5.0.1 on 2024-02-21 14:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Noheru', '0008_rename_user_post_creator_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_name',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='post',
            name='post_publish_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 21, 8, 18, 52, 886116)),
        ),
    ]
