# Generated by Django 5.0.1 on 2024-02-13 14:30

import fernet_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20, unique=True, verbose_name='Username')),
                ('password', fernet_fields.fields.EncryptedCharField(max_length=20, verbose_name='Password')),
                ('email', fernet_fields.fields.EncryptedEmailField(max_length=254, verbose_name='Email')),
                ('signature', models.CharField(default='Hey! write something here', max_length=100, verbose_name='Signature phrase')),
            ],
        ),
    ]
