# Generated by Django 5.0.1 on 2024-01-20 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContractType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract', models.CharField(choices=[('FT', 'Full time'), ('PT', 'Part time')], max_length=2, verbose_name='Tipo de contrato')),
            ],
        ),
        migrations.CreateModel(
            name='TeachersInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre/s')),
                ('lastname1', models.CharField(max_length=100, verbose_name='Apellido 1')),
                ('lastname2', models.CharField(max_length=100, verbose_name='Apellido 1')),
                ('age', models.PositiveIntegerField(verbose_name='Edad')),
                ('maloOrFemale', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, verbose_name='Sexo')),
                ('contractType', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Teachers.contracttype')),
            ],
        ),
    ]
