# Generated by Django 5.0.1 on 2024-01-21 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracttype',
            name='contract',
            field=models.CharField(choices=[('Full Time', 'Full time'), ('Part Time', 'Part time')], max_length=9, verbose_name='Tipo de contrato'),
        ),
    ]
