# Generated by Django 5.0.1 on 2024-01-21 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers', '0002_alter_contracttype_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachersinfo',
            name='contractType',
            field=models.CharField(choices=[('Full Time', 'Full time'), ('Part Time', 'Part time')], max_length=100, verbose_name='Tipo de contrato'),
        ),
        migrations.DeleteModel(
            name='ContractType',
        ),
    ]
